#!/usr/bin/env bash
# Per-machine, one-shot install: RE2 + cre2.
# Idempotent — safe to rerun (e.g. after `pacman -Syu` bumps re2's SONAME).
set -euo pipefail

echo "[re2-mojo install] 1/3 — pacman: re2 + abseil-cpp + build deps"
sudo pacman -S --needed re2 abseil-cpp cmake pkgconf base-devel

echo "[re2-mojo install] 2/3 — cre2: clone + autotools build + install"
BUILD_DIR=$(mktemp -d)
trap 'rm -rf "$BUILD_DIR"' EXIT
git clone --depth 1 https://github.com/marcomaggi/cre2.git "$BUILD_DIR"
cd "$BUILD_DIR"

# Patch two upstream bugs in cre2 master vs modern g++ + automake:
# (a) src/cre2.cpp uses strlen() without #include <cstring>; recent g++ enforces.
# (b) doc/version.texi is normally autogenerated by automake at autogen.sh time
#     but newer automake doesn't always emit it; provide a stub so the texinfo
#     doc build doesn't break the whole `make` invocation.
sed -i '/^#include "cre2.h"$/a #include <cstring>' src/cre2.cpp
mkdir -p doc
cat > doc/version.texi <<'TEXI'
@set UPDATED 1 January 2026
@set UPDATED-MONTH January 2026
@set EDITION 0.4.0
@set VERSION 0.4.0
TEXI

sh autogen.sh
./configure --prefix=/usr/local
make -j"$(nproc)"
sudo make install

# Arch (and some other distros) don't include /usr/local/lib in ld.so search
# paths by default. Register it once so libcre2.so resolves by short name.
if ! grep -qsr '^/usr/local/lib$' /etc/ld.so.conf /etc/ld.so.conf.d/ 2>/dev/null; then
  echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/usrlocal.conf >/dev/null
fi
sudo ldconfig

echo "[re2-mojo install] 3/3 — sanity check"
if ldconfig -p | grep -q libcre2; then
  echo "OK: libcre2 installed."
  pkg-config --modversion cre2 2>/dev/null && true
else
  echo "ERROR: libcre2 not found after install"
  exit 1
fi
